import type { Metadata } from "next";
import "./globals.css";
import { NextUiProvider } from "@/lib/providers/NextUIProvider";
import MyContextProvider from "@/lib/providers/MyContextProvider";
import { Saira } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";

const saira = Saira({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${saira.className} min-h-screen dark:bg-[#0b000e]`}
        suppressHydrationWarning={true}
      >
        <MyContextProvider>
          <NextUiProvider>
            <Navbar/>
            {children}
            <Footer/>
            </NextUiProvider>
        </MyContextProvider>
      </body>
    </html>
  );
}
