import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };


const layout = ({children}: {children: React.ReactNode}) => {
    return (
        <div>
            {children}
        </div>
    );
};

export default layout;